"""Offline native enforcement evidence: synthetic records only.

Nothing here contacts a host, daemon, provider or custody path. Curator keys are
throwaway Ed25519 keys generated by OpenSSL inside the test directory.
"""

import ast
import base64
import copy
import hashlib
import importlib.util
import json
import os
import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[2]
SCRIPT = ROOT / "infra/scripts/coding-native-evidence.py"
spec = importlib.util.spec_from_file_location("native_evidence", SCRIPT)
assert spec is not None and spec.loader is not None
EVIDENCE = importlib.util.module_from_spec(spec)
spec.loader.exec_module(EVIDENCE)

native_spec = importlib.util.spec_from_file_location(
    "native_policy_for_evidence_tests", ROOT / EVIDENCE.NATIVE_BINDING_FILE
)
assert native_spec is not None and native_spec.loader is not None
NATIVE = importlib.util.module_from_spec(native_spec)
native_spec.loader.exec_module(NATIVE)

CATALOG_DIR = ROOT / "services/dittobench-api/internal/codingenforcement/catalog"
GOLDEN_RECORD = CATALOG_DIR / "testdata/golden-record-v1.json"
CANONICAL_VECTOR = CATALOG_DIR / "testdata/canonical-vector-v1.json"
EXPECTATION_VECTORS = CATALOG_DIR / "testdata/expectation-vectors-v1.json"
# Pinned identically in catalog/canonical_test.go.
GOLDEN_RECORD_SHA256 = (
    "ff14852904db79f180ddacec1f1c1350fe9beea6bf97bbe300771b6a1206cc88"
)
CANONICAL_VECTOR_SHA256 = (
    "1948b8f75bd3f0c25825ed268d2390e89ffe1993a37790ee740c19e5cd491a74"
)


def digest(label: str) -> str:
    return hashlib.sha256(label.encode()).hexdigest()


MACHINE = digest("synthetic-machine-id")
BOOT = "11111111-2222-3333-4444-555555555555"
KERNEL = "6.12.43+deb13-cloud-amd64"
DAEMON = digest("synthetic-daemon")
REVISION = "0123456789abcdef0123456789abcdef01234567"
MANIFEST = digest("release-manifest")
RUNTIME = digest("runtime-archive")
IMAGES = {
    language: digest(f"{language}-image-approval") for language in EVIDENCE.LANGUAGES
}
SUBORDINATE = {
    "gid_count": 65536,
    "gid_start": 100000,
    "uid_count": 65536,
    "uid_start": 100000,
}
ENDPOINTS = sorted(
    [
        {"role": "refusing_proxy", "endpoint_sha256": digest("endpoint-proxy")},
        {"role": "router", "endpoint_sha256": digest("endpoint-router")},
        {"role": "trusted", "endpoint_sha256": digest("endpoint-postgresql")},
        {"role": "trusted", "endpoint_sha256": digest("endpoint-hippius")},
    ],
    key=lambda item: (item["role"], item["endpoint_sha256"]),
)
T0 = 2_000_000_000
FIXED_TOOLS = {
    "catalog_sha256": digest("catalog"),
    "collector_sha256": digest("collector"),
    "evidence_tool_sha256": digest("evidence-tool"),
    "fixtures_sha256": digest("fixtures"),
}
FORBIDDEN_KEY = re.compile(r"(^|_)(approved|ready|readiness|qualified)(_|$)|^approval$")
TOOL_NAMES = (
    "coding-native-evidence",
    "collect-coding-native-enforcement",
    "codingenforcement",
    "dittobench-coding-enforcement-probe",
)


def catalog() -> dict:
    return json.loads((CATALOG_DIR / "catalog-v1.json").read_bytes())


def observed_for(expect: dict) -> dict:
    kind = expect["type"]
    if kind == "outcome_in":
        return {"outcome": expect["accept"][0]}
    if kind == "exact":
        return copy.deepcopy(expect["value"])
    if kind == "profile_equal":
        return {"cgroup": 536870912, "profile": 536870912}
    if kind == "bounded":
        return {"enforced": True, "limit": 1000, "measured": 1000}
    if kind == "supervisor_timeout":
        return {
            "deadline_ms": 5000,
            "elapsed_ms": 5200,
            "exit_code": 124,
            "live_processes": 0,
        }
    if kind == "tests":
        if expect["result"] == "all_pass":
            return {"passed": 3, "total": 3}
        return {"passed": 1, "total": 3}
    assert kind == "subordinate_uid"
    return {"host_uid": SUBORDINATE["uid_start"] + 65531}


def build_record(kind: str, *, tools: dict, pre_sha: str, started: int) -> dict:
    entry = catalog()["kinds"][kind]
    endpoints = ENDPOINTS if kind == "network_enforcement" else []
    trusted = [
        item["endpoint_sha256"] for item in endpoints if item["role"] == "trusted"
    ]
    phases = []
    moment = started
    for phase in entry["phases"]:
        probes = []
        for probe in entry["probes"]:
            if probe["phase"] != phase:
                continue
            scopes: list[tuple[str | None, str | None]]
            if probe["scope"] == "host":
                scopes = [(None, None)]
            elif probe["scope"] == "language":
                scopes = [(language, None) for language in EVIDENCE.LANGUAGES]
            else:
                scopes = [(None, endpoint) for endpoint in trusted]
            for language, endpoint in scopes:
                probes.append(
                    {
                        "id": probe["id"],
                        "language": language,
                        "endpoint_sha256": endpoint,
                        "expect": copy.deepcopy(probe["expect"]),
                        "observed": observed_for(probe["expect"]),
                        "matched": True,
                    }
                )
        probes.sort(
            key=lambda item: (
                item["id"],
                item["language"] or "",
                item["endpoint_sha256"] or "",
            )
        )
        phases.append(
            {
                "name": phase,
                "started_at_unix": moment + 1,
                "completed_at_unix": moment + 2,
                "probes": probes,
            }
        )
        moment += 2
    return {
        "schema": EVIDENCE.RECORD_SCHEMA,
        "kind": kind,
        "coverage": "same_boot",
        "not_covered": ["daemon_restart_recovery", "reboot_recovery"],
        "tolerances_version": EVIDENCE.TOLERANCES["version"],
        "host": {
            "machine_id_sha256": MACHINE,
            "boot_id": BOOT,
            "kernel_release": KERNEL,
            "daemon_identity_sha256": DAEMON,
            "subordinate_ids": dict(SUBORDINATE),
            "router_namespace": "rootless-netns",
        },
        "release": {
            "source_revision": REVISION,
            "release_manifest_sha256": MANIFEST,
            "runtime_archive_sha256": RUNTIME,
            "image_approval_sha256": dict(IMAGES),
        },
        "pre_collection_preflight_sha256": pre_sha,
        "inputs": {name: digest(name) for name in entry["inputs"]},
        "endpoints": copy.deepcopy(endpoints),
        "tools": dict(tools),
        "preconditions": dict(EVIDENCE.PRECONDITIONS),
        "phases": phases,
        "residue": dict(EVIDENCE.RESIDUE),
        "started_at_unix": started,
        "completed_at_unix": moment + 1,
    }


def preflight_value(tool_hashes: dict, checked_at: int) -> dict:
    return {
        "schema": EVIDENCE.PREFLIGHT_SCHEMA,
        "source_revision": REVISION,
        "release_manifest_sha256": MANIFEST,
        "runtime_archive_sha256": RUNTIME,
        "image_approval_sha256": dict(IMAGES),
        "config_sha256": digest("preflight-config"),
        "host": {
            "machine_id_sha256": MACHINE,
            "boot_id": BOOT,
            "kernel_release": KERNEL,
        },
        "daemon_identity_sha256": DAEMON,
        "tool_sha256": dict(tool_hashes),
        "nft_snapshot_sha256": digest("nft"),
        "checked_at_unix": checked_at,
        "host_preflight_passed": True,
        "pending_host_qualification": list(EVIDENCE.PREFLIGHT_PENDING),
        "runtime_qualification": False,
        "private_execution_ready": False,
        "shadow_only": True,
        "weight_eligible": False,
    }


def stdout_bytes(value: dict) -> bytes:
    return (json.dumps(value, sort_keys=True) + "\n").encode()


def canonical(value) -> bytes:
    return EVIDENCE.canonical_bytes(value)


def find_probe(record: dict, probe_id: str, language=None, endpoint=None) -> dict:
    for phase in record["phases"]:
        for probe in phase["probes"]:
            if (probe["id"], probe["language"], probe["endpoint_sha256"]) == (
                probe_id,
                language,
                endpoint,
            ):
                return probe
    raise AssertionError(probe_id)


def keys_of(value) -> set[str]:
    if isinstance(value, dict):
        return set(value) | {key for item in value.values() for key in keys_of(item)}
    if isinstance(value, list):
        return {key for item in value for key in keys_of(item)}
    return set()


class World:
    """A synthetic reviewed checkout, private store and passing evidence set."""

    def __init__(self, tmp_path: Path) -> None:
        self.tmp = tmp_path
        self.checkout = tmp_path / "checkout"
        for relative in (
            EVIDENCE.CATALOG_FILE,
            EVIDENCE.TOOL_FILES["evidence_tool_sha256"],
            EVIDENCE.NATIVE_BINDING_FILE,
            EVIDENCE.NATIVE_RUNNER_FILE,
        ):
            target = self.checkout / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / relative, target)
        collector = self.checkout / EVIDENCE.TOOL_FILES["collector_sha256"]
        collector.write_bytes(b"# synthetic collector for tests\n")
        fixtures = self.checkout / EVIDENCE.FIXTURE_ROOT
        (fixtures / "python").mkdir(parents=True)
        (fixtures / "python/fork_exec.py").write_bytes(b"# synthetic\n")
        (fixtures / "README.md").write_bytes(b"synthetic fixtures\n")
        self.preflight_tools = {}
        for relative in EVIDENCE.PREFLIGHT_TOOL_FILES:
            target = self.checkout / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(f"# synthetic {relative}\n".encode())
            self.preflight_tools[relative] = hashlib.sha256(
                target.read_bytes()
            ).hexdigest()
        self.store = tmp_path / "store"
        self.store.mkdir()
        self.store.chmod(0o700)
        self.tools = EVIDENCE.Checkout(self.checkout).tools()
        self.catalog = catalog()
        self.pre_raw = stdout_bytes(preflight_value(self.preflight_tools, T0))
        self.pre_sha = self.put(self.pre_raw)
        self.records = {
            kind: build_record(
                kind, tools=self.tools, pre_sha=self.pre_sha, started=T0 + 100 * (i + 1)
            )
            for i, kind in enumerate(EVIDENCE.KINDS)
        }
        self.post_value = preflight_value(self.preflight_tools, T0 + 4000)
        self.custody_value = {
            "schema": EVIDENCE.CUSTODY_SCHEMA,
            "custody_evidence_sha256": digest("custody-evidence"),
            "machine_id_sha256": MACHINE,
            "boot_id": BOOT,
            "bound_at_unix": T0 + 4100,
        }

    def put(self, raw: bytes) -> str:
        path = self.store / hashlib.sha256(raw).hexdigest()
        if path.exists():
            return path.name
        with EVIDENCE.Store(self.store) as store:
            return store.put(raw)

    def selection(self, **overrides) -> dict:
        result = {
            "host_preflight": self.put(stdout_bytes(self.post_value)),
            **{
                kind: self.put(canonical(self.records[kind])) for kind in EVIDENCE.KINDS
            },
            "private_input_custody": self.put(canonical(self.custody_value)),
        }
        result.update(overrides)
        return result

    def open(self):
        return EVIDENCE.Store(self.store), EVIDENCE.Checkout(self.checkout)

    def review(self, **overrides):
        store, checkout = self.open()
        with store:
            return EVIDENCE.review(store, checkout, self.selection(**overrides))

    def verify(self, record_shas, preflight_sha=None):
        store, checkout = self.open()
        preflight = preflight_sha or self.selection()["host_preflight"]
        with store:
            return EVIDENCE.verify(store, checkout, preflight, record_shas)

    def verify_record(self, record: dict) -> str | None:
        result, _ok = self.verify([self.put(canonical(record))])
        return result["records"][0]["failure"]


@pytest.fixture
def world(tmp_path):
    return World(tmp_path)


# ---------------------------------------------------------------------------
# Canonical encoding, golden vectors and Go/Python parity


TRICKY = {
    "ascii": "plain <>&'/",
    "controls": "\x00\x01\b\t\n\x0b\f\r\x1f\x7f",
    "escapes": 'quote" backslash\\ slash/',
    "separators": "line\u2028paragraph\u2029",
    "unicode": "caf\u00e9 \u65e5\u672c \U0001f600",
    "integers": [0, -1, 9223372036854775807, -9223372036854775808],
    "literals": [True, False, None],
    "empty": {"list": [], "object": {}, "string": ""},
    "order": {"b": 1, "a": 2, "B": 3, "_": 4, "aa": 5, "\u00e9": 6},
}


def golden_record() -> dict:
    return build_record(
        "cleanup_recovery",
        tools=FIXED_TOOLS,
        pre_sha=digest("pre-preflight"),
        started=T0,
    )


def test_golden_record_is_pinned_in_both_languages():
    raw = GOLDEN_RECORD.read_bytes()
    assert canonical(golden_record()) == raw
    assert hashlib.sha256(raw).hexdigest() == GOLDEN_RECORD_SHA256
    assert EVIDENCE.parse_record_envelope(raw)["kind"] == "cleanup_recovery"
    go_test = (CATALOG_DIR / "canonical_test.go").read_text()
    assert re.search(rf'goldenRecordSHA256\s*=\s*"{GOLDEN_RECORD_SHA256}"', go_test)


def test_canonical_vector_is_pinned_in_both_languages():
    raw = CANONICAL_VECTOR.read_bytes()
    assert canonical(TRICKY) == raw
    assert hashlib.sha256(raw).hexdigest() == CANONICAL_VECTOR_SHA256
    assert EVIDENCE.parse_canonical(raw, "vector") == TRICKY
    assert b"\\u2028" in raw and b"\\u2029" in raw and b"\\ud83d\\ude00" in raw
    assert raw.isascii() and not raw.endswith(b"\n")
    go_test = (CATALOG_DIR / "canonical_test.go").read_text()
    assert re.search(
        rf'canonicalVectorSHA256\s*=\s*"{CANONICAL_VECTOR_SHA256}"', go_test
    )


def test_canonical_form_is_the_native_qualification_form():
    run = (ROOT / EVIDENCE.NATIVE_RUNNER_FILE).read_text()
    assert 'json.dumps(value, sort_keys=True, separators=(",", ":")).encode()' in run
    value = {"z": [1, "\u2028"], "a": {"b": None}}
    assert (
        canonical(value)
        == json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    )


@pytest.mark.parametrize(
    ("raw", "reason"),
    [
        (b'{"a": 1}', "not canonical"),
        (b'{"a":1}\n', "not canonical"),
        (b'{"b":1,"a":2}', "not canonical"),
        ('{"a":"\u2028"}'.encode(), "not canonical"),
        (b'{"a":"\\u00E9"}', "not canonical"),
        (b'{"a":-0}', "not canonical"),
        (b'{"a":1,"a":1}', "duplicate key"),
        (b'{"a":1.0}', "must be integers"),
        (b'{"a":1e3}', "must be integers"),
        (b'{"a":NaN}', "finite integers"),
        (b'{"a":9223372036854775808}', "outside int64"),
        (b'{"a":"\\udc00"}', "lone surrogate"),
        (b'{"a":"\xff"}', "not valid JSON"),
        (b"[" * 20 + b"]" * 20, "nested too deeply"),
    ],
)
def test_canonical_parse_refusals(raw, reason):
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        EVIDENCE.parse_canonical(raw, "value")


GO_TOLERANCES = {
    "version": "TolerancesVersion",
    "cpu_usage_max_permille_of_quota": "CPUUsageMaxPermilleOfQuota",
    "memory_peak_max_permille_of_limit": "MemoryPeakMaxPermilleOfLimit",
    "pids_max_permille_of_limit": "PidsMaxPermilleOfLimit",
    "nofile_max_permille_of_limit": "NofileMaxPermilleOfLimit",
    "scratch_max_permille_of_limit": "ScratchMaxPermilleOfLimit",
    "log_max_permille_of_limit": "LogMaxPermilleOfLimit",
    "timeout_elapsed_max_permille_of_deadline": "TimeoutElapsedMaxPermilleOfDeadline",
}


def test_go_embeds_the_same_catalog_file_python_reads():
    source = (CATALOG_DIR / "catalog.go").read_text()
    assert "//go:embed catalog-v1.json" in source
    assert (ROOT / EVIDENCE.CATALOG_FILE) == CATALOG_DIR / "catalog-v1.json"
    assert set(GO_TOLERANCES) == set(EVIDENCE.TOLERANCES)
    for name, constant in GO_TOLERANCES.items():
        value = EVIDENCE.TOLERANCES[name]
        literal = f'"{value}"' if isinstance(value, str) else str(value)
        assert re.search(rf"\b{constant}\s*=\s*{re.escape(literal)}\n", source), name
    assert re.search(r"\bFreshnessMaxSeconds\s*=\s*21600\n", source)
    assert re.search(r"\bCoverage\s*=\s*\"same_boot\"\n", source)


def test_expectation_vectors_agree_with_go():
    vectors = json.loads(EXPECTATION_VECTORS.read_bytes())
    assert (
        vectors["schema"]
        == "dittobench-coding-native-enforcement-expectation-vectors-v1"
    )
    outcomes = set(catalog()["outcomes"])
    results = set()
    for vector in vectors["vectors"]:
        EVIDENCE._validate_expect(vector["expect"], outcomes, vector["name"])
        try:
            matched = EVIDENCE.evaluate(
                vector["expect"],
                vector["observed"],
                vectors["subordinate_ids"],
                outcomes,
            )
        except EVIDENCE.Refusal:
            outcome = "invalid"
        else:
            outcome = "matched" if matched else "unmatched"
        assert outcome == vector["result"], vector["name"]
        results.add(outcome)
    assert results == {"matched", "unmatched", "invalid"}
    assert "vectorsFile" in (CATALOG_DIR / "expect_test.go").read_text()


# ---------------------------------------------------------------------------
# Catalog


def test_catalog_defines_every_required_probe_set():
    value = EVIDENCE.load_catalog((CATALOG_DIR / "catalog-v1.json").read_bytes())
    network = value["kinds"]["network_enforcement"]
    first = network["probes"][0]
    assert first == {
        "id": "candidate.router.source",
        "phase": "active",
        "scope": "host",
        "expect": {"type": "outcome_in", "accept": ["container_address"]},
    }
    ids = {probe["id"] for probe in network["probes"]}
    assert {"candidate.proxy.connect", "candidate.proxy.forward"} <= ids
    assert network["endpoint_roles"]["refusing_proxy"] == {"min": 1, "max": 1}
    handshake = next(
        p for p in network["probes"] if p["id"] == "worker.trusted.handshake"
    )
    assert handshake["scope"] == "trusted_endpoint"
    for kind in ("resource_enforcement", "preexec_confinement"):
        assert {p["scope"] for p in value["kinds"][kind]["probes"]} == {"language"}
    assert value["languages"] == ["go", "node", "python", "rust"]
    assert value["not_covered"] == ["daemon_restart_recovery", "reboot_recovery"]
    assert value["tolerances"]["cpu_usage_max_permille_of_quota"] == 1150
    all_ids = {p["id"] for k in value["kinds"].values() for p in k["probes"]}
    assert not any("reboot" in item or "restart" in item for item in all_ids)


def mutate_catalog(change):
    value = catalog()
    change(value)
    return json.dumps(value).encode()


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (
            lambda c: c["tolerances"].update(cpu_usage_max_permille_of_quota=1200),
            "tolerances differ",
        ),
        (
            lambda c: c.update(not_covered=["daemon_restart_recovery"]),
            "not_covered differs",
        ),
        (lambda c: c.update(coverage="cross_boot"), "coverage differs"),
        (lambda c: c.update(extra=True), "keys are not the closed set"),
        (
            lambda c: c["kinds"]["cleanup_recovery"]["probes"].append(
                copy.deepcopy(c["kinds"]["cleanup_recovery"]["probes"][0])
            ),
            "malformed or repeated",
        ),
        (
            lambda c: c["kinds"]["cleanup_recovery"]["probes"][0]["expect"].update(
                type="anything"
            ),
            "type unknown",
        ),
        (
            lambda c: c["kinds"]["network_enforcement"]["probes"][0]["expect"].update(
                accept=["teleported"]
            ),
            "accepted outcomes",
        ),
        (
            lambda c: c["kinds"]["cleanup_recovery"]["phases"].append("reboot"),
            "phase without probes",
        ),
        (
            lambda c: c["kinds"]["resource_enforcement"]["probes"][4]["expect"].update(
                tolerance="version"
            ),
            "tolerance is unknown",
        ),
    ],
)
def test_catalog_refusals(change, reason):
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        EVIDENCE.load_catalog(mutate_catalog(change))


def test_preflight_format_matches_the_inspector():
    host_spec = importlib.util.spec_from_file_location(
        "preflight_for_evidence_tests",
        ROOT / "infra/scripts/inspect-coding-native-host.py",
    )
    assert host_spec is not None and host_spec.loader is not None
    host = importlib.util.module_from_spec(host_spec)
    host_spec.loader.exec_module(host)
    assert host.TOOL_FILES == EVIDENCE.PREFLIGHT_TOOL_FILES
    assert host.PENDING == EVIDENCE.PREFLIGHT_PENDING
    tree = ast.parse((ROOT / "infra/scripts/inspect-coding-native-host.py").read_text())
    inspect = next(
        node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "inspect_host"
    )
    returned = next(
        node
        for node in ast.walk(inspect)
        if isinstance(node, ast.Return) and isinstance(node.value, ast.Dict)
    )
    assert isinstance(returned.value, ast.Dict)
    keys = {key.value for key in returned.value.keys if isinstance(key, ast.Constant)}
    assert keys == EVIDENCE.PREFLIGHT_KEYS
    main = next(
        node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "main"
    )
    assert "print(json.dumps(inspect_host(config), sort_keys=True))" in ast.unparse(
        main
    )


# ---------------------------------------------------------------------------
# Store


def test_retain_writes_exclusive_private_objects(world, capsys):
    source = world.tmp / "record.json"
    raw = canonical(world.records["cleanup_recovery"])
    source.write_bytes(raw)
    code = EVIDENCE.main(
        [
            "retain",
            "--store",
            str(world.store),
            "--type",
            "record",
            "--input",
            str(source),
        ]
    )
    output = json.loads(capsys.readouterr().out)
    assert code == 0
    assert output == {
        "retained_sha256": hashlib.sha256(raw).hexdigest(),
        "type": "record",
    }
    stored = world.store / output["retained_sha256"]
    assert stat.S_IMODE(stored.stat().st_mode) == 0o400
    assert sorted(path.name for path in world.store.iterdir()) == sorted(
        [world.pre_sha, output["retained_sha256"]]
    )
    with EVIDENCE.Store(world.store) as store:
        assert store.get(output["retained_sha256"]) == raw
        with pytest.raises(EVIDENCE.Refusal, match="already retained"):
            store.put(raw)
    assert not [path for path in world.store.iterdir() if path.name.startswith(".")]


@pytest.mark.parametrize(
    ("case", "reason"),
    [
        ("group readable", "mode 0700 and owned by the invoking user"),
        ("world readable", "mode 0700 and owned by the invoking user"),
        ("other owner", "mode 0700 and owned by the invoking user"),
        ("other ancestor owner", "store ancestor has another owner"),
        ("writable ancestor", "store ancestor is writable by others"),
        ("relative", "must be absolute"),
        ("symlink", "must be canonical"),
        ("missing", "not an existing directory"),
    ],
)
def test_store_refusals(world, monkeypatch, case, reason):
    path = world.store
    uid = os.getuid()
    if case == "group readable":
        world.store.chmod(0o750)
    elif case == "world readable":
        world.store.chmod(0o755)
    elif case == "other owner":
        monkeypatch.setattr(EVIDENCE, "_protected_ancestors", lambda _path: None)
        monkeypatch.setattr(EVIDENCE.os, "geteuid", lambda: uid + 1)
    elif case == "other ancestor owner":
        monkeypatch.setattr(EVIDENCE.os, "geteuid", lambda: uid + 1)
    elif case == "writable ancestor":
        parent = world.tmp / "shared"
        parent.mkdir()
        parent.chmod(0o777)
        path = parent / "store"
        path.mkdir()
        path.chmod(0o700)
    elif case == "relative":
        path = Path("relative/store")
    elif case == "symlink":
        path = world.tmp / "link"
        path.symlink_to(world.store)
    else:
        shutil.rmtree(world.store)
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        EVIDENCE.Store(path)


def test_store_refuses_tampered_or_loose_objects(world):
    target = world.store / world.pre_sha
    with EVIDENCE.Store(world.store) as store:
        target.chmod(0o600)
        with pytest.raises(EVIDENCE.Refusal, match="private single-link"):
            store.get(world.pre_sha)
        target.write_bytes(world.pre_raw.replace(b"true", b"true "))
        target.chmod(0o400)
        with pytest.raises(EVIDENCE.Refusal, match="does not match its digest"):
            store.get(world.pre_sha)
        other = world.put(b"{}")
        os.link(world.store / other, world.tmp / "second-link")
        with pytest.raises(EVIDENCE.Refusal, match="private single-link"):
            store.get(other)
        link = digest("linked")
        (world.store / link).symlink_to(world.store / other)
        with pytest.raises(EVIDENCE.Refusal, match="not retained"):
            store.get(link)
        with pytest.raises(EVIDENCE.Refusal, match="not retained"):
            store.get(digest("absent"))
        with pytest.raises(EVIDENCE.Refusal, match="digest is malformed"):
            store.get("../" + world.pre_sha[:61])


@pytest.mark.parametrize(
    ("kind", "raw", "reason"),
    [
        (
            "record",
            lambda w: json.dumps(w.records["cleanup_recovery"]).encode(),
            "not canonical",
        ),
        (
            "record",
            lambda w: canonical({**w.records["cleanup_recovery"], "approved": True}),
            "closed set",
        ),
        ("host-preflight", lambda w: canonical(w.post_value), "not verbatim"),
        ("custody-binding", lambda w: stdout_bytes(w.custody_value), "not canonical"),
    ],
)
def test_retain_refuses_malformed_inputs(world, capsys, kind, raw, reason):
    source = world.tmp / "input.json"
    source.write_bytes(raw(world))
    code = EVIDENCE.main(
        ["retain", "--store", str(world.store), "--type", kind, "--input", str(source)]
    )
    assert code == 1
    assert re.search(reason, capsys.readouterr().err)
    assert sorted(path.name for path in world.store.iterdir()) == [world.pre_sha]


# ---------------------------------------------------------------------------
# verify


def test_every_kind_verifies(world, capsys):
    selection = world.selection()
    result, ok = world.verify([selection[kind] for kind in EVIDENCE.KINDS])
    assert ok, result
    arguments = [
        "verify",
        "--store",
        str(world.store),
        "--checkout",
        str(world.checkout),
    ]
    arguments += ["--host-preflight", selection["host_preflight"]]
    for kind in EVIDENCE.KINDS:
        arguments += ["--record", selection[kind]]
    assert EVIDENCE.main(arguments) == 0
    printed = capsys.readouterr().out.encode()
    assert EVIDENCE.parse_canonical(printed, "verification")["verified"] is True


TRUSTED = [item["endpoint_sha256"] for item in ENDPOINTS if item["role"] == "trusted"]


def network(change):
    return ("network_enforcement", change)


def cleanup(change):
    return ("cleanup_recovery", change)


def set_path(*path, value):
    def change(record):
        target = record
        for key in path[:-1]:
            target = target[key]
        target[path[-1]] = value

    return change


def drop_probe(probe_id, endpoint=None):
    def change(record):
        for phase in record["phases"]:
            phase["probes"] = [
                p
                for p in phase["probes"]
                if (p["id"], p["endpoint_sha256"]) != (probe_id, endpoint)
            ]

    return change


def edit_probe(probe_id, endpoint=None, language=None, **fields):
    def change(record):
        find_probe(record, probe_id, language, endpoint).update(copy.deepcopy(fields))

    return change


def add_cleanup_probe(record):
    phase = record["phases"][0]
    extra = copy.deepcopy(phase["probes"][0])
    extra["id"] = "cleanup.reboot.absent"
    phase["probes"].append(extra)


def repeat_probe(record):
    phase = record["phases"][0]
    phase["probes"].append(copy.deepcopy(phase["probes"][0]))


def move_probe(record):
    moved = record["phases"][0]["probes"].pop()
    record["phases"][1]["probes"].append(moved)
    record["phases"][1]["probes"].sort(key=lambda p: p["id"])


def reverse_probes(record):
    record["phases"][0]["probes"].reverse()


def swap_phases(record):
    record["phases"][0], record["phases"][1] = record["phases"][1], record["phases"][0]


def unsort_endpoints(record):
    record["endpoints"].reverse()


RECORD_REFUSALS = [
    (network(set_path("approved", value=True)), "keys are not the closed set"),
    (network(set_path("ready", value=True)), "keys are not the closed set"),
    (network(lambda r: r.pop("residue")), "keys are not the closed set"),
    (
        network(
            set_path("schema", value="dittobench-coding-native-enforcement-evidence-v2")
        ),
        "schema is unknown",
    ),
    (network(set_path("kind", value="reboot_recovery")), "kind is unknown"),
    (
        cleanup(set_path("coverage", value="cross_boot")),
        "coverage beyond the same boot",
    ),
    (
        cleanup(set_path("not_covered", value=["daemon_restart_recovery"])),
        "coverage beyond the same boot",
    ),
    (cleanup(set_path("not_covered", value=[])), "coverage beyond the same boot"),
    (cleanup(set_path("tolerances_version", value="v0")), "tolerances version differs"),
    (
        network(set_path("host", "machine_id_sha256", value=digest("other-machine"))),
        "pre-collection preflight machine differs",
    ),
    (
        network(
            set_path("host", "boot_id", value="99999999-2222-3333-4444-555555555555")
        ),
        "preflight boot differs",
    ),
    (
        network(set_path("host", "kernel_release", value="6.1.0")),
        "preflight kernel differs",
    ),
    (
        network(
            set_path("host", "daemon_identity_sha256", value=digest("other-daemon"))
        ),
        "preflight daemon differs",
    ),
    (
        network(set_path("host", "router_namespace", value="slirp4netns")),
        "router namespace is unknown",
    ),
    (
        network(set_path("host", "subordinate_ids", "uid_count", value=1000)),
        "subordinate ids are malformed",
    ),
    (
        network(set_path("release", "source_revision", value="f" * 40)),
        "source_revision differs",
    ),
    (
        network(set_path("release", "release_manifest_sha256", value=digest("x"))),
        "release_manifest_sha256 differs",
    ),
    (
        network(set_path("release", "runtime_archive_sha256", value=digest("x"))),
        "runtime_archive_sha256 differs",
    ),
    (
        network(
            set_path("release", "image_approval_sha256", "rust", value=digest("x"))
        ),
        "image_approval_sha256 differs",
    ),
    (
        network(lambda r: r["release"]["image_approval_sha256"].pop("rust")),
        "image approvals are malformed",
    ),
    (
        network(set_path("pre_collection_preflight_sha256", value=digest("absent"))),
        "not retained",
    ),
    (network(set_path("inputs", value={})), "inputs keys"),
    (
        network(
            set_path("inputs", "connectivity_profile_sha256", value="10.20.0.7:5432")
        ),
        "input malformed",
    ),
    (network(lambda r: r["endpoints"].pop(0)), "refusing_proxy endpoints"),
    (
        network(set_path("endpoints", 1, "endpoint_sha256", value="10.30.0.4:18080")),
        "endpoint hash is malformed",
    ),
    (network(unsort_endpoints), "endpoints are not sorted"),
    (cleanup(set_path("endpoints", value=ENDPOINTS)), "role is not allowed"),
    (
        network(set_path("tools", "collector_sha256", value=digest("operator-built"))),
        "tool hashes differ",
    ),
    (
        network(set_path("tools", "catalog_sha256", value=digest("x"))),
        "tool hashes differ",
    ),
    (
        network(set_path("tools", "fixtures_sha256", value=digest("x"))),
        "tool hashes differ",
    ),
    (
        network(set_path("preconditions", "worker_active", value=True)),
        "preconditions failed",
    ),
    (
        network(set_path("preconditions", "daemon_containers", value=1)),
        "preconditions failed",
    ),
    (cleanup(set_path("residue", "containers", value=1)), "residue is not empty"),
    (
        cleanup(set_path("residue", "custody_socket_present", value=True)),
        "residue is not empty",
    ),
    (cleanup(swap_phases), "phases differ from the catalog order"),
    (
        cleanup(set_path("phases", 1, "started_at_unix", value=T0)),
        "phase timestamps are out of order",
    ),
    (
        cleanup(set_path("completed_at_unix", value=T0 + 400)),
        "completed before its last phase",
    ),
    (
        network(drop_probe("candidate.router.source")),
        "missing probe candidate.router.source",
    ),
    (
        network(drop_probe("worker.trusted.handshake", TRUSTED[1])),
        "missing probe worker.trusted.handshake",
    ),
    (
        network(drop_probe("candidate.proxy.forward")),
        "missing probe candidate.proxy.forward",
    ),
    (cleanup(add_cleanup_probe), "unexpected probe cleanup.reboot.absent"),
    (cleanup(repeat_probe), "repeats probe"),
    (cleanup(move_probe), "wrong phase"),
    (
        network(
            edit_probe(
                "candidate.dns",
                expect={"type": "outcome_in", "accept": ["connected", "refused"]},
            )
        ),
        "expectation differs from the catalog",
    ),
    (
        network(edit_probe("candidate.dns", observed={"outcome": "connected"})),
        "matched value is misreported",
    ),
    (
        network(
            edit_probe("candidate.router.source", observed={"outcome": "host_address"})
        ),
        "matched value is misreported",
    ),
    (
        network(edit_probe("candidate.dns", matched=False)),
        "matched value is misreported",
    ),
    (
        network(
            edit_probe(
                "candidate.dns", observed={"outcome": "connected"}, matched=False
            )
        ),
        "probe candidate.dns did not match",
    ),
    (
        network(
            edit_probe(
                "candidate.router.source",
                observed={"outcome": "host_address"},
                matched=False,
            )
        ),
        "probe candidate.router.source did not match",
    ),
    (
        network(
            edit_probe(
                "candidate.dns", observed={"outcome": "probe_error"}, matched=False
            )
        ),
        "did not match",
    ),
    (
        network(edit_probe("candidate.dns", observed={"outcome": "teleported"})),
        "outcome is unknown",
    ),
    (
        network(
            edit_probe(
                "worker.trusted.handshake",
                TRUSTED[0],
                observed={"outcome": "handshake_completed", "rows": 1},
            )
        ),
        "observed keys",
    ),
    (
        network(
            edit_probe("executor.interfaces", observed={"interfaces": ["10.0.0.2"]})
        ),
        "observed list is malformed",
    ),
    (
        network(
            edit_probe(
                "executor.interfaces",
                observed={"interfaces": ["eth0", "lo"]},
                matched=False,
            )
        ),
        "did not match",
    ),
    (
        network(lambda r: find_probe(r, "candidate.dns").update(language="python")),
        "unexpected probe candidate.dns",
    ),
    (network(edit_probe("candidate.dns", matched=1)), "not a boolean"),
    (network(reverse_probes), "not sorted"),
    (
        cleanup(
            edit_probe(
                "cleanup.rerun.consumed_marker",
                observed={"outcome": "accepted"},
                matched=False,
            )
        ),
        "did not match",
    ),
]


@pytest.mark.parametrize(("case", "reason"), RECORD_REFUSALS)
def test_record_refusals(world, case, reason):
    kind, change = case
    record = copy.deepcopy(world.records[kind])
    change(record)
    failure = world.verify_record(record)
    assert failure is not None and re.search(reason, failure), failure


def resource_edit(probe_id, language, **fields):
    return ("resource_enforcement", edit_probe(probe_id, language=language, **fields))


def preexec_edit(probe_id, language, **fields):
    return ("preexec_confinement", edit_probe(probe_id, language=language, **fields))


EXPECTATION_REFUSALS = [
    (
        resource_edit(
            "harness.cpu_throttle",
            "go",
            observed={"enforced": True, "limit": 1000, "measured": 1151},
        ),
        "misreported",
    ),
    (
        resource_edit(
            "harness.cpu_throttle",
            "go",
            observed={"enforced": True, "limit": 1000, "measured": 1150},
        ),
        None,
    ),
    (
        resource_edit(
            "executor_grading.pids_cap",
            "rust",
            observed={"enforced": True, "limit": 64, "measured": 65},
        ),
        "misreported",
    ),
    (
        resource_edit(
            "executor_grading.memory_oom",
            "node",
            observed={"enforced": False, "limit": 1000, "measured": 900},
        ),
        "misreported",
    ),
    (
        resource_edit(
            "executor_authoring.memory_max",
            "python",
            observed={"cgroup": 1, "profile": 2},
        ),
        "misreported",
    ),
    (
        resource_edit(
            "executor_authoring.memory_swap_max",
            "python",
            observed={"swap_max_bytes": 1},
        ),
        "misreported",
    ),
    (
        resource_edit(
            "harness.supervisor_timeout",
            "go",
            observed={
                "deadline_ms": 5000,
                "elapsed_ms": 5501,
                "exit_code": 124,
                "live_processes": 0,
            },
        ),
        "misreported",
    ),
    (
        resource_edit(
            "harness.supervisor_timeout",
            "go",
            observed={
                "deadline_ms": 5000,
                "elapsed_ms": 5200,
                "exit_code": 124,
                "live_processes": 1,
            },
        ),
        "misreported",
    ),
    (
        resource_edit(
            "harness.log_bound",
            "go",
            observed={"enforced": "true", "limit": 1, "measured": 1},
        ),
        "observed value is malformed",
    ),
    (
        preexec_edit("control.pass", "rust", observed={"passed": 0, "total": 0}),
        "misreported",
    ),
    (
        preexec_edit("control.wrong", "rust", observed={"passed": 3, "total": 3}),
        "misreported",
    ),
    (
        preexec_edit("control.wrong", "rust", observed={"passed": 4, "total": 3}),
        "observed value is malformed",
    ),
    (
        preexec_edit("identity.host_uid", "node", observed={"host_uid": 0}),
        "misreported",
    ),
    (
        preexec_edit("identity.host_uid", "node", observed={"host_uid": 165536}),
        "misreported",
    ),
    (preexec_edit("identity.uid", "node", observed={"uid": 0}), "misreported"),
    (
        preexec_edit("identity.uid", "node", observed={"uid": True}),
        "observed value is malformed",
    ),
    (
        preexec_edit("hostile.ptrace", "python", observed={"outcome": "permitted"}),
        "misreported",
    ),
    (
        preexec_edit(
            "hostile.credential_env", "python", observed={"outcome": "present"}
        ),
        "misreported",
    ),
]


@pytest.mark.parametrize(("case", "reason"), EXPECTATION_REFUSALS)
def test_expectation_semantics_in_records(world, case, reason):
    kind, change = case
    record = copy.deepcopy(world.records[kind])
    change(record)
    failure = world.verify_record(record)
    if reason is None:
        assert failure is None
    else:
        assert failure is not None and re.search(reason, failure), failure


def test_preflight_binding_and_order_refusals(world):
    record = world.records["network_enforcement"]
    late_pre = world.put(stdout_bytes(preflight_value(world.preflight_tools, T0 + 101)))
    assert "pre-collection preflight is later" in world.verify_record(
        {**record, "pre_collection_preflight_sha256": late_pre}
    )
    other = preflight_value(world.preflight_tools, T0)
    other["host"]["machine_id_sha256"] = digest("elsewhere")
    assert "pre-collection preflight machine differs" in world.verify_record(
        {**record, "pre_collection_preflight_sha256": world.put(stdout_bytes(other))}
    )

    early_post = world.put(
        stdout_bytes(preflight_value(world.preflight_tools, T0 + 105))
    )
    result, ok = world.verify([world.put(canonical(record))], preflight_sha=early_post)
    assert not ok
    assert "earlier than the last collection record" in result["records"][0]["failure"]

    result, ok = world.verify(
        [world.put(canonical(record))], preflight_sha=world.pre_sha
    )
    assert (
        not ok
        and "separate post-collection preflight" in result["records"][0]["failure"]
    )

    long_record = copy.deepcopy(record)
    long_record["completed_at_unix"] = long_record["started_at_unix"] + 21601
    late = world.put(stdout_bytes(preflight_value(world.preflight_tools, T0 + 30000)))
    result, ok = world.verify([world.put(canonical(long_record))], preflight_sha=late)
    assert not ok and "freshness window" in result["records"][0]["failure"]


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (lambda v: v.update(host_preflight_passed=False), "did not pass"),
        (lambda v: v.update(private_execution_ready=True), "readiness flags differ"),
        (lambda v: v.update(pending_host_qualification=[]), "pending list differs"),
        (
            lambda v: v["tool_sha256"].update(
                {EVIDENCE.PREFLIGHT_TOOL_FILES[0]: digest("x")}
            ),
            "tool hash differs",
        ),
        (lambda v: v.update(extra=1), "keys are not the closed set"),
    ],
)
def test_host_preflight_refusals(world, change, reason):
    value = preflight_value(world.preflight_tools, T0 + 4000)
    change(value)
    sha = world.put(stdout_bytes(value))
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        world.verify([world.selection()["network_enforcement"]], preflight_sha=sha)


def test_non_verbatim_preflight_is_refused(world):
    sha = world.put(canonical(world.post_value))
    with pytest.raises(EVIDENCE.Refusal, match="not verbatim"):
        world.verify([world.selection()["network_enforcement"]], preflight_sha=sha)


def test_reviewed_checkout_tool_drift_fails_the_record(world):
    selection = world.selection()
    collector = world.checkout / EVIDENCE.TOOL_FILES["collector_sha256"]
    collector.write_bytes(b"# later operator-built collector\n")
    result, ok = world.verify([selection["network_enforcement"]])
    assert not ok and "tool hashes differ" in result["records"][0]["failure"]
    collector.write_bytes(b"# synthetic collector for tests\n")
    (world.checkout / EVIDENCE.FIXTURE_ROOT / "extra.py").write_bytes(b"#\n")
    result, ok = world.verify([selection["network_enforcement"]])
    assert not ok and "tool hashes differ" in result["records"][0]["failure"]


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (
            lambda w: (w.checkout / EVIDENCE.TOOL_FILES["collector_sha256"]).unlink(),
            "checkout is missing",
        ),
        (
            lambda w: (w.checkout / EVIDENCE.FIXTURE_ROOT / "link.py").symlink_to(
                "/etc/hostname"
            ),
            "is not a file",
        ),
        (
            lambda w: (w.checkout / EVIDENCE.CATALOG_FILE).write_bytes(
                mutate_catalog(
                    lambda c: c["tolerances"].update(
                        cpu_usage_max_permille_of_quota=2000
                    )
                )
            ),
            "tolerances differ",
        ),
        (
            lambda w: (w.checkout / EVIDENCE.PREFLIGHT_TOOL_FILES[2]).write_bytes(
                b"# drift\n"
            ),
            "tool hash differs",
        ),
    ],
)
def test_reviewed_checkout_refusals(world, change, reason):
    selection = world.selection()
    change(world)
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        world.verify([selection["network_enforcement"]], selection["host_preflight"])


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (lambda r: r["host"].update(router_namespace="host"), "router namespace"),
        (
            lambda r: r["host"]["subordinate_ids"].update(gid_start=200000),
            "subordinate ids",
        ),
        (
            lambda r: r["inputs"].update(
                execution_profile_sha256=digest("other-profile")
            ),
            "execution_profile_sha256",
        ),
    ],
)
def test_records_must_agree(world, change, reason):
    other = copy.deepcopy(world.records["preexec_confinement"])
    change(other)
    selection = world.selection()
    result, ok = world.verify(
        [selection["resource_enforcement"], world.put(canonical(other))]
    )
    assert not ok
    assert all(item["verified"] for item in result["records"])
    assert reason in result["consistency"]["failure"]


def test_repeated_record_is_refused(world):
    sha = world.selection()["cleanup_recovery"]
    result, ok = world.verify([sha, sha])
    assert not ok and "repeated" in result["consistency"]["failure"]


def test_malformed_shapes_are_refusals_not_crashes(world):
    record = copy.deepcopy(world.records["network_enforcement"])
    record["kind"] = ["network_enforcement"]
    record["host"]["router_namespace"] = {"mode": "host"}
    assert world.verify_record(record) is not None
    record = copy.deepcopy(world.records["network_enforcement"])
    record["phases"][0]["probes"][0]["id"] = ["candidate"]
    assert world.verify_record(record) is not None
    record = copy.deepcopy(world.records["network_enforcement"])
    record["phases"][0]["probes"][0]["id"] = "10.20.0.7:5432"
    assert world.verify_record(record) == "record has an unexpected probe"
    record = copy.deepcopy(world.records["network_enforcement"])
    record["phases"][0]["probes"][0]["observed"] = {"outcome": ["connected"]}
    assert "outcome is unknown" in world.verify_record(record)


# ---------------------------------------------------------------------------
# review


def test_review_assembles_six_digests_without_approval(world, capsys):
    selection = world.selection()
    value, ok = world.review()
    assert ok
    assert value["evidence_sha256"] == selection
    assert list(value["evidence_sha256"]) == list(EVIDENCE.EVIDENCE)
    assert value["approval_generated"] is False
    assert value["coverage"] == "same_boot"
    assert value["not_covered"] == ["daemon_restart_recovery", "reboot_recovery"]
    assert value["host"]["router_namespace"] == "rootless-netns"
    assert value["window"] == {
        "custody_bound_at_unix": T0 + 4100,
        "earliest_started_at_unix": T0 + 100,
        "host_preflight_checked_at_unix": T0 + 4000,
        "latest_completed_at_unix": world.records["cleanup_recovery"][
            "completed_at_unix"
        ],
    }
    assert all(item["verified"] for item in value["verification"].values())
    assert not {key for key in keys_of(value) if FORBIDDEN_KEY.search(key)}

    arguments = [
        "review",
        "--store",
        str(world.store),
        "--checkout",
        str(world.checkout),
    ]
    for name, sha in selection.items():
        arguments += ["--" + name.replace("_", "-"), sha]
    assert EVIDENCE.main(arguments) == 0
    printed = capsys.readouterr().out.encode()
    assert printed == canonical(value)


def test_failed_review_prints_no_digest_map(world, capsys):
    broken = copy.deepcopy(world.records["resource_enforcement"])
    edit_probe(
        "harness.cpu_throttle",
        language="go",
        observed={"enforced": True, "limit": 1000, "measured": 2000},
        matched=False,
    )(broken)
    selection = world.selection(resource_enforcement=world.put(canonical(broken)))
    arguments = [
        "review",
        "--store",
        str(world.store),
        "--checkout",
        str(world.checkout),
    ]
    for name, sha in selection.items():
        arguments += ["--" + name.replace("_", "-"), sha]
    assert EVIDENCE.main(arguments) == 1
    printed = capsys.readouterr().out.encode()
    value = EVIDENCE.parse_canonical(printed, "review")
    assert set(value) == EVIDENCE.REVIEW_KEYS
    assert value["verified"] is False and value["approval_generated"] is False
    assert "did not match" in value["verification"]["resource_enforcement"]["failure"]
    for sha in selection.values():
        assert sha.encode() not in printed
    assert not re.search(
        rb"[0-9a-f]{64}", printed.replace(value["catalog_sha256"].encode(), b"")
    )


@pytest.mark.parametrize(
    ("overrides", "item", "reason"),
    [
        (
            lambda w: {"resource_enforcement": w.selection()["network_enforcement"]},
            "resource_enforcement",
            "record is not resource_enforcement",
        ),
        (
            lambda w: {"host_preflight": w.pre_sha},
            "network_enforcement",
            "separate post-collection preflight",
        ),
        (
            lambda w: {"private_input_custody": w.put(stdout_bytes(w.custody_value))},
            "private_input_custody",
            "not canonical",
        ),
    ],
)
def test_review_item_refusals(world, overrides, item, reason):
    value, ok = world.review(**overrides(world))
    assert not ok and "evidence_sha256" not in value
    assert reason in value["verification"][item]["failure"]


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (
            lambda c: c.update(boot_id="99999999-2222-3333-4444-555555555555"),
            "custody binding boot differs",
        ),
        (
            lambda c: c.update(machine_id_sha256=digest("elsewhere")),
            "custody binding machine differs",
        ),
        (lambda c: c.update(bound_at_unix=T0 + 30000), "freshness window"),
    ],
)
def test_review_cross_binds_custody_to_machine_and_boot(world, change, reason):
    change(world.custody_value)
    value, ok = world.review()
    assert not ok and "evidence_sha256" not in value
    assert reason in value["consistency"]["failure"]


def test_review_refuses_a_reused_digest(world):
    selection = world.selection()
    value, ok = world.review(resource_enforcement=selection["network_enforcement"])
    assert not ok
    assert "reused" in value["consistency"]["failure"]


def test_review_refuses_a_record_that_claims_more_than_same_boot(world):
    world.records["cleanup_recovery"]["not_covered"] = ["daemon_restart_recovery"]
    value, ok = world.review()
    assert not ok
    assert (
        "beyond the same boot" in value["verification"]["cleanup_recovery"]["failure"]
    )


def policy_arguments():
    return {
        "source": REVISION,
        "plan_sha": digest("plan"),
        "helper_sha": digest("helper"),
        "controls": 16,
        "jobs": 1,
        "now": T0 + 4200,
    }


def test_native_policy_rejects_every_review_and_verifier_output(world):
    passing, ok = world.review()
    assert ok
    world.custody_value["boot_id"] = "99999999-2222-3333-4444-555555555555"
    failing, ok = world.review()
    assert not ok
    verification, _ = world.verify([world.selection()["cleanup_recovery"]])
    outputs = [passing, failing, verification]
    for output in outputs:
        with pytest.raises(ValueError, match="native control approval rejected"):
            NATIVE.policy(copy.deepcopy(output), **policy_arguments())
        # Even with every approval field grafted on, the review keys make it fail.
        grafted = {**approval_value(passing), **output}
        with pytest.raises(ValueError, match="native control approval rejected"):
            NATIVE.policy(grafted, **policy_arguments())
        assert not {key for key in keys_of(output) if FORBIDDEN_KEY.search(key)}


# ---------------------------------------------------------------------------
# check-approval


def openssl_3() -> str | None:
    path = shutil.which("openssl")
    if path is None:
        return None
    version = subprocess.run([path, "version"], capture_output=True, check=False)
    return path if version.stdout.startswith(b"OpenSSL 3.") else None


OPENSSL = openssl_3()
if OPENSSL is None and os.environ.get("CI"):
    raise RuntimeError("CI must provide OpenSSL 3 for curator signature tests")
needs_openssl = pytest.mark.skipif(OPENSSL is None, reason="OpenSSL 3 is unavailable")
# Only used by tests that skip when OpenSSL 3 is unavailable.
OPENSSL_BIN = OPENSSL or "/usr/bin/openssl"


class Curator:
    def __init__(self, directory: Path, name: str) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        self.private = directory / f"{name}.key"
        self.public = directory / f"{name}.pem"
        subprocess.run(
            [
                OPENSSL_BIN,
                "genpkey",
                "-algorithm",
                "ed25519",
                "-out",
                str(self.private),
            ],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            [
                OPENSSL_BIN,
                "pkey",
                "-in",
                str(self.private),
                "-pubout",
                "-out",
                str(self.public),
            ],
            check=True,
            capture_output=True,
        )
        der = base64.b64decode(b"".join(self.public.read_bytes().splitlines()[1:-1]))
        self.key_sha256 = hashlib.sha256(der[12:]).hexdigest()

    def sign(self, raw: bytes, path: Path) -> Path:
        message = path.with_suffix(".message")
        message.write_bytes(raw)
        subprocess.run(
            [
                OPENSSL_BIN,
                "pkeyutl",
                "-sign",
                "-inkey",
                str(self.private),
                "-rawin",
                "-in",
                str(message),
                "-out",
                str(path),
            ],
            check=True,
            capture_output=True,
        )
        return path


def approval_value(review_value: dict, **overrides) -> dict:
    value = {
        "schema": EVIDENCE.APPROVAL_SCHEMA,
        "purpose": "private-compatibility-once",
        "source_revision": REVISION,
        "release_manifest_sha256": MANIFEST,
        "plan_sha256": digest("plan"),
        "helper_sha256": digest("helper"),
        "runner_sha256": hashlib.sha256(
            (ROOT / EVIDENCE.NATIVE_RUNNER_FILE).read_bytes()
        ).hexdigest(),
        "binding_sha256": hashlib.sha256(
            (ROOT / EVIDENCE.NATIVE_BINDING_FILE).read_bytes()
        ).hexdigest(),
        "machine_id_sha256": MACHINE,
        "boot_id": BOOT,
        "issued_at_unix": T0 + 4200,
        "expires_at_unix": T0 + 4200 + 3600,
        "controls": 16,
        "max_jobs": 2,
        "images": {
            language: {
                "image_ref": f"coding-runtime.invalid/{language}/runtime@sha256:"
                + digest(language + "-manifest"),
                "config_digest": "sha256:" + digest(language + "-config"),
                "approval_sha256": IMAGES[language],
                "driver_profile": NATIVE.PROFILES[language],
            }
            for language in EVIDENCE.LANGUAGES
        },
        "evidence_sha256": dict(review_value.get("evidence_sha256", {})),
        "shadow_only": True,
        "weight_eligible": False,
    }
    value.update(overrides)
    return value


class Approval:
    def __init__(self, world: World) -> None:
        self.world = world
        self.directory = world.tmp / "curator"
        self.curator = Curator(self.directory, "curator")
        review_value, ok = world.review()
        assert ok
        self.review_value = review_value
        self.review = self.directory / "review.json"
        self.review.write_bytes(canonical(review_value))
        self.value = approval_value(review_value)

    def write(self, value=None, *, signer=None, raw=None) -> tuple[Path, Path]:
        body = (
            raw
            if raw is not None
            else json.dumps(value or self.value, indent=2, sort_keys=True).encode()
            + b"\n"
        )
        approval = self.directory / "approval.json"
        approval.write_bytes(body)
        signature = (signer or self.curator).sign(body, self.directory / "approval.sig")
        return approval, signature

    def check(
        self,
        *,
        approval=None,
        signature=None,
        review=None,
        public=None,
        pin=None,
        openssl=None,
    ):
        if approval is None or signature is None:
            approval, signature = self.write()
        store, checkout = self.world.open()
        with store:
            return EVIDENCE.check_approval(
                store=store,
                checkout=checkout,
                review_raw=(review or self.review).read_bytes(),
                approval_raw=approval.read_bytes(),
                signature=signature.read_bytes(),
                public_key_raw=(public or self.curator.public).read_bytes(),
                curator_signing_key_sha256=pin or self.curator.key_sha256,
                openssl=Path(openssl or OPENSSL_BIN),
            )

    def arguments(self, approval: Path, signature: Path) -> list[str]:
        return [
            "check-approval",
            "--store",
            str(self.world.store),
            "--checkout",
            str(self.world.checkout),
            "--review",
            str(self.review),
            "--approval",
            str(approval),
            "--signature",
            str(signature),
            "--curator-public-key",
            str(self.curator.public),
            "--curator-signing-key-sha256",
            self.curator.key_sha256,
            "--openssl",
            OPENSSL_BIN,
        ]


@pytest.fixture
def signed(world):
    if OPENSSL is None:
        pytest.skip("OpenSSL 3 is unavailable")
    return Approval(world)


@needs_openssl
def test_check_approval_accepts_a_signed_consistent_approval(signed, capsys):
    approval, signature = signed.write()
    assert EVIDENCE.main(signed.arguments(approval, signature)) == 0
    output = json.loads(capsys.readouterr().out)
    assert output == {
        "schema": EVIDENCE.CHECK_SCHEMA,
        "approval_generated": False,
        "checked_approval_sha256": hashlib.sha256(approval.read_bytes()).hexdigest(),
        "curator_signing_key_sha256": signed.curator.key_sha256,
        "review_sha256": hashlib.sha256(signed.review.read_bytes()).hexdigest(),
        "signature_sha256": hashlib.sha256(signature.read_bytes()).hexdigest(),
        "consistent": True,
    }
    with pytest.raises(ValueError, match="native control approval rejected"):
        NATIVE.policy(output, **policy_arguments())


@needs_openssl
def test_check_approval_refuses_without_a_signature(signed, capsys):
    approval, signature = signed.write()
    signature.unlink()
    assert EVIDENCE.main(signed.arguments(approval, signature)) == 1
    assert "curator signature is missing" in capsys.readouterr().err
    arguments = signed.arguments(approval, signature)
    index = arguments.index("--signature")
    del arguments[index : index + 2]
    with pytest.raises(SystemExit):
        EVIDENCE.main(arguments)
    assert "--signature" in capsys.readouterr().err


@needs_openssl
def test_check_approval_signature_refusals(signed):
    approval, signature = signed.write()
    raw = signature.read_bytes()
    short = signed.directory / "short.sig"
    short.write_bytes(raw[:63])
    with pytest.raises(EVIDENCE.Refusal, match="signature is malformed"):
        signed.check(approval=approval, signature=short)

    tampered = signed.directory / "tampered.json"
    tampered.write_bytes(
        approval.read_bytes().replace(b'"controls": 16', b'"controls": 32')
    )
    with pytest.raises(EVIDENCE.Refusal, match="does not verify"):
        signed.check(approval=tampered, signature=signature)

    other = Curator(signed.directory, "other")
    other_signature = other.sign(approval.read_bytes(), signed.directory / "other.sig")
    with pytest.raises(EVIDENCE.Refusal, match="does not verify"):
        signed.check(approval=approval, signature=other_signature)
    with pytest.raises(EVIDENCE.Refusal, match="differs from the pinned identity"):
        signed.check(approval=approval, signature=signature, public=other.public)

    for algorithm, reason in (
        ("x25519", "must be Ed25519"),
        ("EC", "not a PEM public key"),
    ):
        foreign = signed.directory / f"{algorithm}.pem"
        options = ["-pkeyopt", "ec_paramgen_curve:P-256"] if algorithm == "EC" else []
        key = signed.directory / f"{algorithm}.key"
        subprocess.run(
            [
                OPENSSL_BIN,
                "genpkey",
                "-algorithm",
                algorithm,
                *options,
                "-out",
                str(key),
            ],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            [OPENSSL_BIN, "pkey", "-in", str(key), "-pubout", "-out", str(foreign)],
            check=True,
            capture_output=True,
        )
        with pytest.raises(EVIDENCE.Refusal, match=reason):
            signed.check(approval=approval, signature=signature, public=foreign)

    fake = signed.directory / "libressl"
    fake.write_text("#!/bin/sh\necho 'LibreSSL 3.3.6'\n")
    fake.chmod(0o700)
    with pytest.raises(EVIDENCE.Refusal, match="OpenSSL 3 is required"):
        signed.check(approval=approval, signature=signature, openssl=str(fake))


@needs_openssl
def test_curator_verification_is_pure_ed25519():
    # RFC 8032 section 7.1, TEST 2.
    key = bytes.fromhex(
        "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c"
    )
    signature = bytes.fromhex(
        "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da"
        "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00"
    )
    EVIDENCE.verify_ed25519(Path(OPENSSL_BIN), key, b"\x72", signature)
    with pytest.raises(EVIDENCE.Refusal, match="does not verify"):
        EVIDENCE.verify_ed25519(Path(OPENSSL_BIN), key, b"\x73", signature)
    # S + L is the same point equation but a non-canonical encoding.
    order = 2**252 + 27742317777372353535851937790883648493
    s = int.from_bytes(signature[32:], "little") + order
    malleated = signature[:32] + s.to_bytes(32, "little")
    with pytest.raises(EVIDENCE.Refusal, match="does not verify"):
        EVIDENCE.verify_ed25519(Path(OPENSSL_BIN), key, b"\x72", malleated)


def mismatch(**overrides):
    return lambda value: value.update(overrides)


@needs_openssl
@pytest.mark.parametrize(
    ("change", "reason"),
    [
        *[
            (
                lambda value, name=name: value["evidence_sha256"].update(
                    {name: digest("other")}
                ),
                "evidence digests differ",
            )
            for name in EVIDENCE.EVIDENCE
        ],
        (mismatch(machine_id_sha256=digest("elsewhere")), "machine differs"),
        (mismatch(boot_id="99999999-2222-3333-4444-555555555555"), "boot differs"),
        (mismatch(source_revision="f" * 40), "source revision differs"),
        (
            mismatch(release_manifest_sha256=digest("other-release")),
            "release manifest differs",
        ),
        (
            lambda value: value["images"]["go"].update(
                approval_sha256=digest("other-go")
            ),
            "go image approval differs",
        ),
        (mismatch(weight_eligible=True), "rejected by native.policy"),
        (mismatch(approved=True), "rejected by native.policy"),
        (mismatch(expires_at_unix=T0 + 4200 + 86401), "rejected by native.policy"),
        (mismatch(binding_sha256=digest("edited-native")), "binding hash differs"),
        (mismatch(runner_sha256=digest("edited-run")), "runner hash differs"),
        (
            mismatch(schema="dittobench-coding-native-controls-approval-v1"),
            "schema is unknown",
        ),
        (
            mismatch(issued_at_unix=T0 + 4050, expires_at_unix=T0 + 7000),
            "issued before its evidence was complete",
        ),
        (
            mismatch(issued_at_unix=T0 + 100 + 21601, expires_at_unix=T0 + 30000),
            "older than six hours",
        ),
    ],
)
def test_check_approval_refuses_inconsistent_approvals(signed, change, reason):
    value = copy.deepcopy(signed.value)
    change(value)
    approval, signature = signed.write(value)
    with pytest.raises(EVIDENCE.Refusal, match=reason):
        signed.check(approval=approval, signature=signature)


@needs_openssl
def test_check_approval_refuses_review_tampering(signed, world):
    approval, signature = signed.write()
    review = signed.directory / "edited-review.json"

    claims = copy.deepcopy(signed.review_value)
    claims["not_covered"] = ["daemon_restart_recovery"]
    review.write_bytes(canonical(claims))
    with pytest.raises(EVIDENCE.Refusal, match="beyond the same boot"):
        signed.check(approval=approval, signature=signature, review=review)

    edited = copy.deepcopy(signed.review_value)
    edited["window"]["earliest_started_at_unix"] = T0 + 4000
    review.write_bytes(canonical(edited))
    with pytest.raises(EVIDENCE.Refusal, match="differs from the evidence it names"):
        signed.check(approval=approval, signature=signature, review=review)

    review.write_bytes(json.dumps(signed.review_value).encode())
    with pytest.raises(EVIDENCE.Refusal, match="not canonical"):
        signed.check(approval=approval, signature=signature, review=review)

    world.custody_value["boot_id"] = "99999999-2222-3333-4444-555555555555"
    failing, _ = world.review()
    review.write_bytes(canonical(failing))
    with pytest.raises(EVIDENCE.Refusal, match="did not verify every record"):
        signed.check(approval=approval, signature=signature, review=review)

    network_sha = signed.review_value["evidence_sha256"]["network_enforcement"]
    (world.store / network_sha).unlink()
    with pytest.raises(EVIDENCE.Refusal, match="no longer verifies"):
        signed.check(approval=approval, signature=signature)


# ---------------------------------------------------------------------------
# Boundaries: no probes, no custody paths, no workflow


def test_retain_verify_and_review_run_no_subprocess(world, monkeypatch):
    def forbidden(*_args, **_kwargs):
        raise AssertionError("evidence tool started a process")

    monkeypatch.setattr(subprocess, "run", forbidden)
    monkeypatch.setattr(subprocess, "Popen", forbidden)
    monkeypatch.setattr(os, "system", forbidden)
    value, ok = world.review()
    assert ok
    world.verify([world.selection()["network_enforcement"]])


@needs_openssl
def test_check_approval_runs_only_openssl(signed, monkeypatch):
    calls = []
    real = subprocess.run

    def record(arguments, **kwargs):
        calls.append(list(arguments))
        return real(arguments, **kwargs)

    approval, signature = signed.write()
    monkeypatch.setattr(EVIDENCE.subprocess, "run", record)
    signed.check(approval=approval, signature=signature)
    assert [call[:2] for call in calls if call[0] == OPENSSL_BIN] == [
        [OPENSSL_BIN, "version"],
        [OPENSSL_BIN, "pkeyutl"],
    ]
    assert all(call[0] == OPENSSL_BIN for call in calls)


def test_evidence_tool_names_no_host_or_custody_surface():
    source = SCRIPT.read_text()
    for forbidden in (
        "/var/lib/ditto-coding-custody",
        "/run/ditto-coding",
        "docker",
        "/usr/sbin/nft",
        "systemctl",
        "/etc/machine-id",
        "/proc/",
        "urllib",
        "import socket",
    ):
        assert forbidden not in source, forbidden
    assert "subprocess.run(" in source and "Popen" not in source


def test_pinned_native_consumers_stay_untouched():
    native = (ROOT / EVIDENCE.NATIVE_BINDING_FILE).read_text()
    inspector = (ROOT / "infra/scripts/inspect-coding-native-host.py").read_text()
    for source in (native, inspector, (ROOT / EVIDENCE.NATIVE_RUNNER_FILE).read_text()):
        for name in TOOL_NAMES:
            assert name not in source


def test_collectors_never_enter_the_operate_workflow():
    workflows = ROOT / ".github/workflows"
    operate_surface = [
        workflows / "coding-hosted-operate.yml",
        ROOT / "infra/scripts/coding-hosted-verify.py",
        ROOT / "infra/github/coding-hosted-operate-environment.json",
        ROOT / "infra/github/coding-hosted-operate-ruleset.json",
    ]
    for path in operate_surface:
        if path.exists():
            text = path.read_text()
            assert not [name for name in TOOL_NAMES if name in text], path
    referencing = sorted(
        path.name
        for path in workflows.glob("*.y*ml")
        if any(name in path.read_text() for name in TOOL_NAMES)
    )
    # Only the offline regression job may name the tool, and it has no host,
    # secret or deployment authority.
    assert referencing == ["coding-native-release.yml"]
    ci = (workflows / "coding-native-release.yml").read_text()
    for forbidden in (
        "secrets.",
        "environment:",
        "id-token",
        "ssh",
        "gcloud",
        "collect-coding-native-enforcement",
    ):
        assert forbidden not in ci


def test_script_runs_isolated_from_the_checkout(world):
    selection = world.selection()
    arguments = [
        sys.executable,
        "-B",
        "-I",
        str(SCRIPT),
        "review",
        "--store",
        str(world.store),
        "--checkout",
        str(world.checkout),
    ]
    for name, sha in selection.items():
        arguments += ["--" + name.replace("_", "-"), sha]
    result = subprocess.run(arguments, capture_output=True, check=False, cwd="/")
    assert result.returncode == 0, result.stderr
    assert json.loads(result.stdout)["evidence_sha256"] == selection
